/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a normal scaffold and kept here so the
// manual MVP scaffold type-checks once dependencies are installed.

